name: "CI"
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
  issues: write
  pull-requests: write
  security-events: write
  actions: write
jobs:

  lint:
    uses: dencanem/ueidbdh/.github/workflows/main.yml@main
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write
      security-events: write
      id-token: write

